"""empty message

Revision ID: 9774efbdace8
Revises: a321d15999ca
Create Date: 2019-05-16 08:54:52.352698

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9774efbdace8'
down_revision = 'a321d15999ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('name', sa.String(length=40), nullable=False))
    op.drop_column('employees', 'last_name')
    op.drop_column('employees', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('first_name', mysql.VARCHAR(length=40), nullable=False))
    op.add_column('employees', sa.Column('last_name', mysql.VARCHAR(length=40), nullable=False))
    op.drop_column('employees', 'name')
    # ### end Alembic commands ###
