"""empty message

Revision ID: a321d15999ca
Revises: 3ef5890b8f84
Create Date: 2019-05-15 13:53:41.735743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a321d15999ca'
down_revision = '3ef5890b8f84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('first_name', sa.String(length=40), nullable=False))
    op.add_column('employees', sa.Column('last_name', sa.String(length=40), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'last_name')
    op.drop_column('employees', 'first_name')
    # ### end Alembic commands ###
